# Using container-based infrastructure
# sudo: false
# enable trusty beta
sudo: required
dist: trusty

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src
        - $HOME/x-tools
        # - $HOME/zlib-install
        # - $HOME/openssl-install
        # - $HOME/pcre-install
        # - $HOME/libsodium-install
        # - $HOME/mbedtls-install
        # - $HOME/libev-install


# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - gperf
            - libncurses5-dev
            - texinfo
            - help2man
            - asciidoc
            - xmlto
            - libncurses5
            - libgmp-dev 
            - nettle-dev
            # - libtool
            # - autogen
            # - automake
            - libstdc++6 
            - net-tools
            - perl
            # - python

# Handle git submodules yourself
git:
    submodules: false
    
# Use sed to replace the SSH URL with the public URL, then initialize submodules
# before_install:
    # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    # - git submodule update --init --recursive
    # - sudo apt-get update -qq
    # - sudo apt-get install libpcre3 libpcre3-dev -y
    
# Building crosstool-NG core
# keep these on at all times because it is fast
install:
    - pwd

# Here is the list of all the standard samples tracked
# by the continuous integration system
env:
    # - CT_SAMPLE=mipsel-unknown-linux-gnu
    matrix:
        # - export PATH=$HOME/x-tools/mipsel-unknown-linux-uclibc/bin:$PATH
        # - TT_BUILD=r2z
        - TT_BUILD=r2j

    global:
        - secure: BRZVkQhpRpE8n7RZ0rZiZSnc2/HyTGyzhFF4iwQs9rXMsRmIVoAEf1vUDExckqI9reJrym+VJP3J3ib+xtczV6JB6C68JtKBWWibvNRTs9Ti2DwY05AYuSnE8opRuUzffv0kyWG3XK+0cW28/uy6lphSQ6uDG7m2Gp/pQrIQtJ42djGYzA6zWO7YS0fPhbgy/7QjxnIUXgavKBHFD53Wlnzw86NtviIDTeC234bpl9BgLJ23ueIdkX4g1kyWYX1ewSRuQOGFnjwcSofzOcMb/gQN4J3P00cWaLhlnl7AYQlkYE+shFTma8XI9+srgrQiakDI6tkOISiVP5zBo6iqw1q23ikObxPIjl28row4VKg3zBQxgD8COlp67YHnDCHp5kl0Nmpyc4/d6fFh72oH34gjDA/9UxaAyrRwKJsuwISoxs4YJskx0g3iSJb3X5V6ilmr1L0Mbk/Xlstd3OGZ4rx3OFBE2+CwQr9Ac2FvZ2vWmPifiUO/LcAZjmkO8DMeICBL7rdu8Z1+sSq2iwAsJaLF6jjaLatjflP/xpyoD++/r2sk/4//saClJA1RcflEvvX4KFMTd25zpaQxvBq1G62b0i0sc+BuWRroR3Vjyudb/ItzHbACeoUAxi/HA6Kqeo2j2STZTkcuKRzBwmW+H4CNafb6tojBMHQpu7apVeU=
        
# Building the standard samples
script:
    # - . ls -l $HOME
    - . $TRAVIS_BUILD_DIR/.travis.sh      # Load the travis environment
    - echo ============================
    - pre_build_prep > /dev/null
    - build_tomato

# On failure displaying the last lines of the log file
after_failure:
    - echo ============= tomato ===============
    - tail -n 1000 ~/advancedTomato.txt
    
    
after_success: . $TRAVIS_BUILD_DIR/update-gh-pages.sh
